key:      AIzaSyAAtzS0w_J0QOuKgEPHEpq8NSvem6MNwNo
cx:       015218215461178039152:3nepwgitpa4
fields:   queries/request/searchTerms,searchInformation/totalResults,items(htmlTitle,link,displayLink,snippet,pagemap(organization,postaladdress,cse_thumbnail/src))
baseUrl:  https://www.googleapis.com/customsearch/v1?
localUrl: http://truck-finder.local/